### ISSUE TITLE
Doesn't Run. Gives Errors. 

### ISSUE THREAD

**Issue by LoneWolf4713** [pauleve/mpd-dynamic#2]
Hey Man, I checked the other issue too, and yes I removed the comments from config file. but it still gives this error:
`2024-01-23 14:32:49,561 Calling MPD connect('localhost', 6600, timeout=None)
Traceback (most recent call last):
  File "/home/prtyksh/.local/bin/mpd-dynamic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/prtyksh/.local/lib/python3.12/site-packages/mpd_dynamic.py", line 288, in main
    probs = get_probs()
            ^^^^^^^^^^^
  File "/home/prtyksh/.local/lib/python3.12/site-packages/mpd_dynamic.py", line 276, in get_probs
    total = sum(weight.values())
            ^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'str'
2024-01-23 14:32:49,630 Calling MPD disconnect()`

what do I do?

**Comment by pauleve** [comment]
can you show your config file (without the secret)?

**Comment by LoneWolf4713** [comment]
here you go
                   
``` 
[spotify]
id = 
secret = 
limit = 30
market = IN
weight = 2

[lastfm]
weight = 1


[mpd]
host = localhost
port = 6600


[playlist]
threshold = 10
extend = 3
```

**Comment by pauleve** [comment]
Can you try with removing the two lines with weight = ...

**Comment by LoneWolf4713** [comment]
Thank you man, it works now. Thank you so much. Really Like This. Thanks!
